plugins:
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.0

Layout/EndOfLine:
  EnforcedStyle: lf

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
