# -*- encoding: utf-8 -*-

require File.expand_path('../lib/kaitai/struct/struct', __FILE__)

Gem::Specification.new do |s|
  s.name = 'kaitai-struct'
  s.version = Kaitai::Struct::VERSION

  s.authors = ['Mikhail Yakshin']
  s.email = 'greycat@kaitai.io'

  s.homepage = 'https://kaitai.io/'
  s.summary = 'Kaitai Struct: runtime library for Ruby'
  s.license = 'MIT'
  s.metadata = {
    'bug_tracker_uri' => 'https://github.com/kaitai-io/kaitai_struct_ruby_runtime/issues',
    'documentation_uri' => 'https://www.rubydoc.info/gems/kaitai-struct',
    'homepage_uri' => s.homepage,
    'source_code_uri' => 'https://github.com/kaitai-io/kaitai_struct_ruby_runtime',
    # See https://guides.rubygems.org/mfa-requirement-opt-in/
    'rubygems_mfa_required' => 'true'
  }
  s.description = <<-DESC
Kaitai Struct is a declarative language used for describe various binary data structures, laid out in files or in memory: i.e. binary file formats, network stream packet formats, etc.

The main idea is that a particular format is described in Kaitai Struct language (.ksy file) and then can be compiled with ksc into source files in one of the supported programming languages. These modules will include a generated code for a parser that can read described data structure from a file / stream and give access to it in a nice, easy-to-comprehend API.

This package provides small runtime library used by code generated by Kaitai Struct compiler.
  DESC

  s.required_ruby_version = '>= 1.9.3'
  s.required_rubygems_version = Gem::Requirement.new('>= 0') if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib']

  s.files = Dir['lib/**/*.rb'] + ['LICENSE', 'README.md']
  s.executables = s.files.grep(%r{^bin/}) { |f| File.basename(f) }
end
