name: Check

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Run tests
        run: bundle exec rspec --force-color

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'
          bundler-cache: true
      - name: Run RuboCop - warnings
        id: rubocop-warnings
        run: bundle exec rubocop --color --fail-level warning --display-only-fail-level-offenses
      - name: Run RuboCop - everything
        run: bundle exec rubocop --color
        continue-on-error: true
        if: ${{ !cancelled() && steps.rubocop-warnings.conclusion != 'skipped' }}
